version: '3.9'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: 'redis:latest'
    ports:
      - "6380:6379"
  web:
    build: .
    command: bash -c "bundle exec rake db:migrate && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    links: 
      - db:db
      - redis:redis  
    volumes:
       - .:/passbase-challenge
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - FIXER_API_KEY=66e62c5ddc5e0af450df3ed2248e09bd
