version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: 'redis:latest'
    ports:
      - "6380:6379"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/take-home-challenge
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FIXER_API_KEY=66e62c5ddc5e0af450df3ed2248e09bd
    tty: true
    stdin_open: true
